### ISSUE TITLE
'Can not decode content-encoding: gzip'

### ISSUE THREAD

**Issue by atomiczsec** [trufflesecurity/EmailGraffiti#2]
Hello, I have tried this python script on Windows 10 and Kali Linux.... getting the same error:

![image](https://user-images.githubusercontent.com/75549184/210461669-7064ff66-499f-47f2-92b9-029b8d214771.png)

**Comment by dxa4481** [comment]
Looks like that email was gzipped. I don't think I've seen that before, the easiest work around I think would be to wrap line 204 in a try catch for `aiohttp.client_exeptions.ClientPayloadError`.

If that works, feel free to open a PR, and I'll merge it
